# Generated by Django 5.0.7 on 2025-09-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.classroom')),
                ('student', models.ManyToManyField(to='schoolapp.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher')),
            ],
        ),
    ]
