# Generated by Django 5.0.7 on 2025-09-08 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_rename_subjects_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schoolapp.classroom'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=20)),
                ('time', models.CharField(choices=[('09:00-10:00', '09:00 - 10:00 AM'), ('10:00-11:00', '10:00 - 11:00 AM'), ('11:00-12:00', '11:00 - 12:00 PM'), ('12:00-01:00', '12:00 - 01:00 PM'), ('01:00-02:00', '01:00 - 02:00 PM'), ('02:00-03:00', '02:00 - 03:00 PM'), ('03:00-04:00', '03:00 - 04:00 PM')], max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.classroom')),
            ],
        ),
    ]
